version: "3"
services:
  prod-app:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    profiles:
      - prod
    networks:
      - default
    depends_on:
      - selenium-webdriver
      - cache
      - postgres
  selenium-webdriver:
    image: selenium/standalone-chrome:latest
    restart: always
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - default

  cache:
    image: redis:latest
    command: redis-server
    hostname: cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: local-network
    driver: bridge
