version: "3"
services:
  prod-app:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    profiles:
      - prod
    networks:
      - default
    depends_on:
      - selenium-webdriver
  selenium-webdriver:
    image: selenium/standalone-chrome:latest
    restart: always
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - default

  cache:
    image: redis:latest
    command: redis-server
    hostname: cache
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    name: local-network
    external: true
    driver: bridge
